### ISSUE TITLE
I copy pasted the product url

### ISSUE THREAD

**Issue by rumi123** [AmmeySaini/Flipkart-Notifier#13]
Traceback (most recent call last):
  File "c:/Users/rumin/Desktop/product alert/Flipkart-Notifier/fk.py", line 97, in main
    if soup.find('button', class_ = '_2AkmmA _3-iCOr wvj5kH').text == 'NOTIFY ME':
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/rumin/Desktop/product alert/Flipkart-Notifier/fk.py", line 105, in main
    if soup.find('button', class_ = '_2AkmmA _2Npkh4 _2MWPVK').text == ' ADD TO CART':
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/rumin/Desktop/product alert/Flipkart-Notifier/fk.py", line 130, in <module>
    main()
  File "c:/Users/rumin/Desktop/product alert/Flipkart-Notifier/fk.py", line 126, in main
    if soup.find('button', class_ = '_2AkmmA _2Npkh4 _2MWPVK _18WSRq')['disabled']:
TypeError: 'NoneType' object is not subscriptable

**Comment by rumi123** [comment]
Class names has been changed in the site
