### ISSUE TITLE
I did what was written in Readme.md

### ISSUE THREAD

**Issue by vjaykrsna** [AmmeySaini/Flipkart-Notifier#8]
$ python fk.py

 _____ _      _   _       _   _  __ _                 |  ___| | __ | \ | | ___ | |_(_)/ _(_) ___ _ __
| |_  | |/ / |  \| |/ _ \| __| | |_| |/ _ \ '__|
|  _| |   <  | |\  | (_) | |_| |  _| |  __/ |
|_|   |_|\_\ |_| \_|\___/ \__|_|_| |_|\___|_|

Paste 1st url, When you are done adding urls input "next" to start script: https://www.flipkart.com/realme-6-comet-white-128-gb/p/itm12516d12e4a46?pid=MOBFPCX7U6C69DSU&lid=LSTMOBFPCX7U6C69DSUXD4ZOQ&marketplace=FLIPKART&pageUID=1599578893997
Paste 2nd url, When you are done adding urls input "next" to start script: next
Enter Your Pincode: 110035
Realme 6 (Comet White, 128 GB)  (8 GB RAM) is in stockTraceback (most recent call last):
  File "fk.py", line 79, in main                          if soup.find('button', class_ = '_2AkmmA _3-iCOr wvj5kH').text == 'NOTIFY ME':
AttributeError: 'NoneType' object has no attribute 'text'
                                                      During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fk.py", line 102, in main
    with app:
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/client.py", line 248, in __enter__
    return self.start()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/sync.py", line 56, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/data/data/com.termux/files/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/methods/utilities/start.py", line 53, in start
    is_authorized = await self.connect()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/methods/auth/connect.py", line 39, in connect
    await self.load_session()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/client.py", line 678, in load_session
    await self.storage.open()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyrogram/storage/file_storage.py", line 116, in open
    self.conn.execute("VACUUM")
sqlite3.DatabaseError: database disk image is malformed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fk.py", line 111, in <module>
    main()
  File "fk.py", line 107, in main
    if soup.find('button', class_ = '_2AkmmA _2Npkh4 _2MWPVK _18WSRq')['disabled']:
TypeError: 'NoneType' object is not subscriptable
$

Still I git so many errors
Little help will be appreciated 🙃

**Comment by sank8dalvi** [comment]
#11 
I have fixed this issue in the above PR but adding a error message for incorrect Telegram Credentials
